# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: osquery
  name: osquery
  namespace: team-security 
spec:
  selector:
    matchLabels:
      k8s-app: osquery
  template:
    metadata:
      labels:
        k8s-app: osquery
    spec:
      shareProcessNamespace: true
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: gjyoung1974/osqueryds:latest
        # image: ubuntu
        # command: ["tail","-f","/dev/null"]
        imagePullPolicy: Always
        name: osquery
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
        - name: procdir
          mountPath: /host/proc
          readOnly: true
        - name: cgroups
          mountPath: /host/sys/fs/cgroup
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
